{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secret.betterAuthSecret | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | b64enc | quote }}
{{- end }}
